site_name: Phylm
site_author: dbatten5
site_url: https://dbatten5.github.io/phylm

theme:
  name: material
  # logo: 'images/logo.bmp'
  features:
    - navigation.instant
  palette:
    primary: deep orange
    accent: blue

nav:
  - Phylm: index.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_root_heading: true
            heading_level: 1
      watch:
        - src
  - autolinks
  - git-revision-date-localized:
      type: timeago
      fallback_to_build_date: true
  - minify:
      minify_html: true

markdown_extensions:
  - abbr
  - def_list
  - admonition
  - markdown_include.include:
      base_path: docs
  - meta
  - toc:
      permalink: true
      baselevel: 2
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: "!!python/name:pymdownx.emoji.to_svg"
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

repo_name: dbatten5/phylm
repo_url: https://github.com/dbatten5/phylm
